import re

with open('generate_q2_excel.py', 'r', encoding='utf-8') as f:
    text = f.read()

start_marker = "for i, (rn_r, rn_a, rn_t) in enumerate(patient_inputs):"
end_marker = "ws.merge_cells(f\\'B{r}:O{r}\\')"

start_idx = text.find(start_marker)

end_idx = text.find(end_marker, start_idx)
if end_idx == -1: 
    # Try unescaped
    end_marker = "ws.merge_cells(f'B{r}:O{r}')"
    end_idx = text.find(end_marker, start_idx)
    
end_idx += len(end_marker)

replacement = """for i, (rn_r, rn_a, rn_t) in enumerate(patient_inputs):
    r = FIRST + i
    patient_num = i + 1

    # Python simulation
    arrival = (patient_num - 1) * 12
    reg_dur = 2 + 6 * rn_r
    reg_end = arrival + reg_dur
    
    doctor = "D1" if rn_a < 0.4 else "D2"
    trt_dur = 10 + 10 * rn_t
    
    if doctor == "D1":
        trt_begin = max(reg_end, d1_free)
    else:
        trt_begin = max(reg_end, d2_free)
        
    q_wait = max(0, trt_begin - reg_end)
    trt_end = trt_begin + trt_dur
    sys_time = trt_end - arrival
    
    if doctor == "D1":
        d1_free = trt_end
    else:
        d2_free = trt_end

    # Write identical UI as before but with static values
    ws.cell(row=r, column=1, value=patient_num).alignment = Alignment(horizontal="center")
    
    cell_b = ws.cell(row=r, column=2, value=arrival)
    cell_b.number_format = '0.00'; cell_b.alignment = Alignment(horizontal="center")
    
    cell_c = ws.cell(row=r, column=3, value=rn_r)
    cell_c.number_format = '0.000'; cell_c.fill = ORANGE_LT
    cell_c.alignment = Alignment(horizontal="center")
    
    cell_d = ws.cell(row=r, column=4, value=reg_dur)
    cell_d.number_format = '0.00'; cell_d.alignment = Alignment(horizontal="center")
    
    cell_e = ws.cell(row=r, column=5, value=reg_end)
    cell_e.number_format = '0.00'; cell_e.alignment = Alignment(horizontal="center")
    
    cell_f = ws.cell(row=r, column=6, value=rn_a)
    cell_f.number_format = '0.000'; cell_f.fill = ORANGE_LT
    cell_f.alignment = Alignment(horizontal="center")
    
    cell_g = ws.cell(row=r, column=7, value=doctor)
    cell_g.alignment = Alignment(horizontal="center")
    
    cell_h = ws.cell(row=r, column=8, value=rn_t)
    cell_h.number_format = '0.000'; cell_h.fill = ORANGE_LT
    cell_h.alignment = Alignment(horizontal="center")
    
    cell_i = ws.cell(row=r, column=9, value=trt_dur)
    cell_i.number_format = '0.00'; cell_i.alignment = Alignment(horizontal="center")
    
    cell_j = ws.cell(row=r, column=10, value=trt_begin)
    cell_j.number_format = '0.00'; cell_j.alignment = Alignment(horizontal="center")
    
    cell_k = ws.cell(row=r, column=11, value=q_wait)
    cell_k.number_format = '0.00'; cell_k.alignment = Alignment(horizontal="center")
    
    cell_l = ws.cell(row=r, column=12, value=trt_end)
    cell_l.number_format = '0.00'; cell_l.alignment = Alignment(horizontal="center")
    
    cell_m = ws.cell(row=r, column=13, value=sys_time)
    cell_m.number_format = '0.00'; cell_m.alignment = Alignment(horizontal="center")
    
    cell_n = ws.cell(row=r, column=14, value=d1_free)
    cell_n.number_format = '0.00'; cell_n.fill = HELPER
    cell_n.alignment = Alignment(horizontal="center")
    cell_n.font = Font(size=9, color="595959")
    
    cell_o = ws.cell(row=r, column=15, value=d2_free)
    cell_o.number_format = '0.00'; cell_o.fill = HELPER
    cell_o.alignment = Alignment(horizontal="center")
    cell_o.font = Font(size=9, color="595959")

# Note about extra RNs
ws['A32'] = "* RN_T for P9 (0.639) and all three RNs for P10 (0.025, 0.275, 0.223) are generated beyond the 27 given."
ws['A32'].font = Font(italic=True, size=9, color="595959")
ws.merge_cells('A32:O32')

bordered(ws, 20, 1, LAST, 13)   # main table gets full border
bordered(ws, 20, 14, LAST, 15)  # helper columns get border too

# ── ROW 34-43 : formula reference ────────────────────────────────────────────
ws['A34'] = "Simulation Note:"
ws['A34'].font = Font(bold=True, size=11)
ws['A34'].fill = LT_BLUE
ws.merge_cells('A34:O34')

formula_notes = [
    ("Simulation Logic", "The dynamic formulas have been removed as requested. The values shown are purely the simulation results generated by Python based on the given parameters, guaranteeing an error-free Excel file.")
]
for offset, (col_name, note) in enumerate(formula_notes, 1):
    r = 34 + offset
    ws.cell(row=r, column=1, value=col_name).font = Font(bold=True)
    ws.cell(row=r, column=1).fill = GREEN_LT
    ws.cell(row=r, column=2, value=note)
    ws.merge_cells(f'B{r}:O{r}')"""

new_content = text[:start_idx] + replacement + text[end_idx:]

with open('generate_q2_excel.py', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Patch applied to Q2.")
