% Settings
fs = 48000;  % Match your complex.wav sampling rate

% complex_recreate.wav is generated by synthesize_recreate.py
% (additive synthesis with comb filter, 4 bursts at ~1.2s intervals)
% This script only generates the comparison spectrogram plot.

% Read both files
[orig, fs_orig] = audioread('complex.wav');
[recreated, fs_rec] = audioread('complex_recreate.wav');
signal = recreated(:,1)';  % ensure row vector

% Plot side-by-side spectrograms using the same settings as main.m
window = hamming(2048);
noverlap = 1536;
nfft = 4096;

[s1, f1, t1] = spectrogram(orig, window, noverlap, nfft, fs_orig);
[s2, f2, t2] = spectrogram(signal(:), window, noverlap, nfft, fs);

S1_db = 10*log10(abs(s1).^2 + eps);
S2_db = 10*log10(abs(s2).^2 + eps);

% Use a common color scale so levels are comparable
clim = [min([S1_db(:); S2_db(:)]), max([S1_db(:); S2_db(:)])];

figure;
subplot(1,2,1);
imagesc(t1, f1, S1_db); axis xy;
title('Original complex.wav');
xlabel('Time (s)'); ylabel('Frequency (Hz)');
caxis(clim);

% Zoom frequency axis a bit (focus on 0–8 kHz)
ylim([0 8000]);

subplot(1,2,2);
imagesc(t2, f2, S2_db); axis xy;
title('Recreated');
xlabel('Time (s)'); ylabel('Frequency (Hz)');
caxis(clim);
ylim([0 8000]);

colormap jet;
colorbar('Position',[0.92 0.11 0.015 0.815]);

% Save combined plot
saveas(gcf, 'complex_comparison.png');