#!/usr/bin/env python3
"""hw3_q3/solve_q3.py

Goal (Q3 bonus): maximize acceptance rate against a *biased* verifier on
graphs generated by `gen_graph` (graphs are intentionally non-3-colorable).

Key idea: learn the verifier's challenge distribution by probing, then
compute a coloring that *minimizes the probability mass* of monochromatic
edges under that distribution.

Empirically, the verifier is heavily biased towards edges incident to a
high-degree / high-mass "hub" vertex (often vertex 0 in graphs generated by
`gen_graph`). We therefore hard-protect all hub-incident edges (always
possible), then solve a weighted Max-3-Cut instance on the remaining sampled
edges using local search.

This file is self-contained and does:
1) generate graphs
2) probe verifier to estimate edge probabilities
3) compute an adversarial coloring that satisfies hot edges
4) measure acceptance using honest_prover.py
"""

from __future__ import annotations

import collections
import math
import os
import queue
import random
import subprocess
import sys
import threading
import time
from dataclasses import dataclass
from typing import DefaultDict, Dict, Iterable, List, Optional, Sequence, Set, Tuple


# ---------------------------- Configuration ----------------------------

NUM_GRAPHS = 20

# Verifier rounds per protocol run (assignment default is often 50)
ROUNDS_PER_PROTOCOL = 50

# How many full protocol trials to estimate acceptance for each graph
TRIALS_PER_GRAPH = 20

# Set `Q3_FAST=1` to speed up development sweeps (fewer trials / less search).
FAST_MODE = os.environ.get("Q3_FAST", "0").strip() == "1"

# Adversarial input choice: for each size, generate multiple candidate graphs
# (still using gen_graph) and keep the one that yields the strongest verifier bias.
try:
    _cand_default = 4 if FAST_MODE else 6
    CANDIDATE_GRAPHS_PER_SIZE = int(os.environ.get("Q3_CANDIDATES", str(_cand_default)).strip())
except Exception:
    CANDIDATE_GRAPHS_PER_SIZE = 4 if FAST_MODE else 6

# Optional: choose a more favorable size schedule (skips tiny weakly-biased graphs)
SIZE_PROFILE = os.environ.get("Q3_SIZE_PROFILE", "default").strip().lower()

def _env_int(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, str(default)).strip())
    except Exception:
        return default


def _env_float(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, str(default)).strip())
    except Exception:
        return default


PROBE_MULT = _env_float("Q3_PROBE_MULT", 1.0)

GRAPHS_DIR = "graphs"
COLORINGS_DIR = "colorings"


@dataclass(frozen=True)
class ProbeConfig:
    rounds: int
    runs: int
    timeout_s: int = 30


@dataclass(frozen=True)
class SolveConfig:
    restarts: int
    steps_per_restart: int
    random_walk_prob: float
    feedback_iters: int
    feedback_rounds: int
    seed: int


def choose_protected_hub_neighbors(
    hub: int,
    edge_counts: Dict[Tuple[int, int], int],
    mass_target: float,
) -> Tuple[Set[int], float]:
    """Choose a subset of hub neighbors covering `mass_target` of hub-incident probe mass.

    Returns (protected_neighbors, covered_mass_fraction).
    """

    hub_items: List[Tuple[int, int]] = []
    total = 0
    for (u, v), w in edge_counts.items():
        if u == hub:
            hub_items.append((v, w))
            total += w
        elif v == hub:
            hub_items.append((u, w))
            total += w

    if total <= 0:
        return set(), 0.0

    hub_items.sort(key=lambda x: x[1], reverse=True)
    protected: Set[int] = set()
    acc = 0
    for nb, w in hub_items:
        protected.add(nb)
        acc += w
        if acc / total >= mass_target:
            break
    return protected, acc / total


BASE_DIR = os.path.dirname(os.path.abspath(__file__))


# ---------------------------- IO + Graph ----------------------------


def ensure_dirs() -> None:
    os.makedirs(os.path.join(BASE_DIR, GRAPHS_DIR), exist_ok=True)
    os.makedirs(os.path.join(BASE_DIR, COLORINGS_DIR), exist_ok=True)


def rel_to_base(path: str) -> str:
    return os.path.relpath(path, BASE_DIR).replace("\\", "/")


def _graph_meta_path(graph_path: str) -> str:
    return graph_path + ".meta"


def _read_size_param(meta_path: str) -> Optional[int]:
    try:
        with open(meta_path, "r", encoding="utf-8") as f:
            s = f.read().strip()
        return int(s)
    except Exception:
        return None


def _write_size_param(meta_path: str, size_param: int) -> None:
    with open(meta_path, "w", encoding="utf-8") as f:
        f.write(str(int(size_param)))


def generate_graph(idx: int, size: int, force_regenerate: bool) -> str:
    filename = os.path.join(BASE_DIR, GRAPHS_DIR, f"G_{idx}.txt")
    meta = _graph_meta_path(filename)
    if os.path.exists(filename) and not force_regenerate:
        if _read_size_param(meta) == size:
            return filename

    cmd = ["wsl", "./gen_graph", "--size", str(size)]
    print(f"Generating graph {idx} (size {size})...", flush=True)
    with open(filename, "w", encoding="utf-8") as f:
        subprocess.run(cmd, cwd=BASE_DIR, stdout=f, check=True)
    _write_size_param(meta, size)
    return filename


def generate_graph_to_path(path: str, size: int) -> None:
    cmd = ["wsl", "./gen_graph", "--size", str(size)]
    # gen_graph is a black box; retry a few times if it exits non-zero.
    last_err: Optional[Exception] = None
    for _ in range(3):
        try:
            with open(path, "w", encoding="utf-8") as f:
                subprocess.run(cmd, cwd=BASE_DIR, stdout=f, check=True)
            return
        except Exception as e:
            last_err = e
            time.sleep(0.05)
    if last_err is not None:
        raise last_err


def estimate_hub_bias(graph_path: str, probe_rounds: int) -> float:
    """Quickly estimate hub mass (fraction of endpoints incident to the most-hit vertex).

    Uses a short probe so we can compare candidate graphs cheaply.
    """

    graph_rel = rel_to_base(graph_path)
    counts = probe_edge_distribution(graph_rel, ProbeConfig(rounds=probe_rounds, runs=1, timeout_s=20))
    if not counts:
        return 0.0
    # Compute hub endpoint mass
    n, _edges = read_graph(graph_path)
    if n <= 0:
        return 0.0
    v_mass = vertex_marginal_mass(n, counts)
    hub = max(range(n), key=lambda v: v_mass[v])
    total = sum(counts.values())
    return v_mass[hub] / max(1, 2 * total)


def compute_adversarial_coloring(
    n: int,
    edges: Sequence[Tuple[int, int]],
    adj: List[List[int]],
    edge_counts: Dict[Tuple[int, int], int],
    solve_cfg: SolveConfig,
    rng: random.Random,
) -> Tuple[List[int], int, float]:
    """Return (colors, hub_vertex, protected_hub_mass).

    Chooses between multiple protection strategies and keeps the one with best predicted acceptance.
    """

    weighted_adj = build_weighted_adj(n, edge_counts)
    v_mass = vertex_marginal_mass(n, edge_counts)
    hub = max(range(n), key=lambda v: v_mass[v])

    unit_adj = build_unit_adj(n, edges)

    # Strategies:
    # - hub-protect at varying strengths
    # - unconstrained (no hub fixed), sometimes better for weakly-biased small graphs
    protect_targets = [0.97, 0.985, 0.995, 1.0]
    if FAST_MODE:
        protect_targets = [0.98, 0.99, 1.0]

    candidates: List[Tuple[Optional[float], float]] = [(None, 0.0)]  # (protect_target, placeholder)
    candidates.extend([(t, 0.0) for t in protect_targets])

    best_colors: Optional[List[int]] = None
    best_forbidden: Optional[List[Set[int]]] = None
    best_protected_hub_mass = 0.0
    best_pred_accept = -1.0
    best_bad_edges = 10**18

    for protect_target, _ in candidates:
        protected_hub_mass = 0.0
        forbidden: List[Set[int]] = [set() for _ in range(n)]

        if protect_target is not None:
            # Fix hub to color 0
            forbidden[hub].update({1, 2})
            protected_neighbors, protected_hub_mass = choose_protected_hub_neighbors(
                hub=hub,
                edge_counts=edge_counts,
                mass_target=protect_target,
            )
            for nb in protected_neighbors:
                forbidden[nb].add(0)

            def random_feasible_coloring() -> List[int]:
                colors = [rng.randrange(3) for _ in range(n)]
                colors[hub] = 0
                for nb in protected_neighbors:
                    colors[nb] = 1 if rng.random() < 0.5 else 2
                for v in range(n):
                    if colors[v] in forbidden[v]:
                        choices = [c for c in (0, 1, 2) if c not in forbidden[v]]
                        colors[v] = choices[0] if choices else 0
                return colors

        else:
            # Unconstrained start
            def random_feasible_coloring() -> List[int]:
                return [rng.randrange(3) for _ in range(n)]

        local_best: Optional[List[int]] = None
        local_best_bad = 10**18
        for _ in range(max(1, solve_cfg.restarts)):
            colors = random_feasible_coloring()

            # Greedy best response pass (weighted)
            order = list(range(n))
            rng.shuffle(order)
            for v in order:
                best_c = colors[v]
                best_local = 10**18
                for c in (0, 1, 2):
                    if c in forbidden[v]:
                        continue
                    local = 0
                    for nb, w in weighted_adj[v]:
                        if c == colors[nb]:
                            local += w
                    if local < best_local:
                        best_local = local
                        best_c = c
                colors[v] = best_c

            local_search_minimize_bad(
                colors=colors,
                weighted_adj=weighted_adj,
                forbidden=forbidden,
                steps=solve_cfg.steps_per_restart,
                random_walk_prob=solve_cfg.random_walk_prob,
                rng=rng,
            )

            bad = total_weighted_bad(colors, weighted_adj)
            if bad < local_best_bad:
                local_best_bad = bad
                local_best = colors

        colors = local_best if local_best is not None else random_feasible_coloring()

        # Reduce overall invalid edges a bit without destroying weighted objective.
        local_search_reduce_total_conflicts(
            colors=colors,
            edges=edges,
            unit_adj=unit_adj,
            weighted_adj=weighted_adj,
            forbidden=forbidden,
            steps=max(20_000 if FAST_MODE else 40_000, solve_cfg.steps_per_restart // 2),
            rng=rng,
            alpha_weighted=14,
            beta_unweighted=2,
            random_walk_prob=0.03,
        )

        bad_w, total_w = weighted_conflict_mass(colors, edge_counts)
        bad_mass = (bad_w / total_w) if total_w else 1.0
        pred_accept = (1.0 - bad_mass) ** ROUNDS_PER_PROTOCOL if bad_mass < 1.0 else 0.0
        bad_edges = count_conflicting_edges(colors, edges)

        if (pred_accept > best_pred_accept) or (abs(pred_accept - best_pred_accept) < 1e-12 and bad_edges < best_bad_edges):
            best_pred_accept = pred_accept
            best_bad_edges = bad_edges
            best_protected_hub_mass = protected_hub_mass
            best_colors = list(colors)
            best_forbidden = forbidden

    if best_colors is None:
        best_colors = [rng.randrange(3) for _ in range(n)]
        best_protected_hub_mass = 0.0

    return best_colors, hub, best_protected_hub_mass


def generate_best_graph(idx: int, size: int, force_regenerate: bool) -> str:
    """Generate multiple graphs for the same size and keep the most exploitable one."""

    final_path = os.path.join(BASE_DIR, GRAPHS_DIR, f"G_{idx}.txt")
    meta = _graph_meta_path(final_path)
    if os.path.exists(final_path) and not force_regenerate:
        if _read_size_param(meta) == size:
            return final_path

    best_path = ""
    best_score = -1.0
    best_tiebreak_bad_edges = 10**18
    probe_rounds = 250 if size <= 40 else 450

    # Cheap solve config for selecting candidates
    sel_cfg = SolveConfig(
        restarts=2 if FAST_MODE else 4,
        steps_per_restart=8_000 if FAST_MODE else 18_000,
        random_walk_prob=0.06,
        feedback_iters=0,
        feedback_rounds=200,
        seed=7777 + size * 17,
    )

    pid = os.getpid()
    cand_paths: List[str] = []

    for k in range(1, CANDIDATE_GRAPHS_PER_SIZE + 1):
        cand_path = os.path.join(BASE_DIR, GRAPHS_DIR, f"G_{idx}_cand{k}_{pid}.txt")
        cand_paths.append(cand_path)
        generate_graph_to_path(cand_path, size)
        if not os.path.exists(cand_path):
            continue

        # Score by predicted acceptance under a cheap probe + cheap solve.
        graph_rel = rel_to_base(cand_path)
        edge_counts = probe_edge_distribution(graph_rel, ProbeConfig(rounds=probe_rounds, runs=1, timeout_s=20))
        n, edges = read_graph(cand_path)
        if n <= 0 or not edge_counts:
            continue
        adj: List[List[int]] = [[] for _ in range(n)]
        for u, v in edges:
            adj[u].append(v)
            adj[v].append(u)
        rng = random.Random(sel_cfg.seed + n)
        colors, _hub, _prot = compute_adversarial_coloring(
            n=n,
            edges=edges,
            adj=adj,
            edge_counts=edge_counts,
            solve_cfg=sel_cfg,
            rng=rng,
        )
        bad_w, total_w = weighted_conflict_mass(colors, edge_counts)
        bad_mass = (bad_w / total_w) if total_w else 1.0
        score = (1.0 - bad_mass) ** ROUNDS_PER_PROTOCOL if bad_mass < 1.0 else 0.0
        bad_edges = count_conflicting_edges(colors, edges)
        if (score > best_score) or (abs(score - best_score) < 1e-12 and bad_edges < best_tiebreak_bad_edges):
            best_score = score
            best_tiebreak_bad_edges = bad_edges
            best_path = cand_path

    # Move best into place, delete the others.
    if best_path:
        try:
            os.replace(best_path, final_path)
        except OSError:
            # Fallback: copy then delete
            with open(best_path, "r", encoding="utf-8") as src, open(final_path, "w", encoding="utf-8") as dst:
                dst.write(src.read())
            os.remove(best_path)
        _write_size_param(meta, size)

    for cand_path in cand_paths:
        if os.path.exists(cand_path):
            try:
                os.remove(cand_path)
            except OSError:
                pass

    return final_path


def read_graph(path: str) -> Tuple[int, List[Tuple[int, int]]]:
    with open(path, "r", encoding="utf-8") as f:
        toks = f.read().split()
    if len(toks) < 2:
        return 0, []

    n = int(toks[0])
    m = int(toks[1])
    edge_data = list(map(int, toks[2:]))
    if len(edge_data) != 2 * m:
        # tolerate minor format issues; parse pairs available
        m = len(edge_data) // 2

    edges: List[Tuple[int, int]] = []
    for i in range(0, 2 * m, 2):
        u = edge_data[i]
        v = edge_data[i + 1]
        if u == v:
            continue
        if u > v:
            u, v = v, u
        edges.append((u, v))
    return n, edges


def write_coloring(path: str, colors: Sequence[int]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for c in colors:
            f.write(f"{int(c)}\n")


# ---------------------------- Probing ----------------------------


def probe_edge_distribution(graph_rel: str, probe: ProbeConfig) -> Dict[Tuple[int, int], int]:
    """Collect many challenges in one (or a few) verifier runs.

    Critical optimization: instead of spawning the verifier per-sample,
    run with `--rounds K` and respond with a fixed non-equal pair (0,1)
    to force the verifier to continue and reveal all K challenged edges.
    """

    counts: DefaultDict[Tuple[int, int], int] = collections.defaultdict(int)

    cmd = ["wsl", "./zk_verifier", "--graph", graph_rel, "--rounds", str(probe.rounds)]
    # If the verifier's sampling adapts to answers, probing with constant answers can skew the
    # distribution. Use random *distinct* pairs to better mimic normal protocol executions.
    rng = random.Random(0)
    distinct_pairs = [(0, 1), (0, 2), (1, 2)]
    for _ in range(probe.runs):
        p = subprocess.Popen(
            cmd,
            cwd=BASE_DIR,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
        )
        assert p.stdin and p.stdout

        # Avoid interactive deadlocks: pre-send enough ANSWER lines up-front.
        # The verifier will consume them as it emits CHALLENGE lines.
        answers: List[str] = []
        for _k in range(probe.rounds + 5):
            a, b = distinct_pairs[rng.randrange(len(distinct_pairs))]
            answers.append(f"ANSWER {a} {b}\n")
        p.stdin.write("".join(answers))
        p.stdin.flush()

        start = time.time()
        for raw in p.stdout:
            if time.time() - start > probe.timeout_s:
                break
            line = raw.strip()
            if line.startswith("CHALLENGE"):
                parts = line.split()
                if len(parts) >= 3:
                    u = int(parts[1])
                    v = int(parts[2])
                    if u > v:
                        u, v = v, u
                    counts[(u, v)] += 1
                continue
            if line.startswith("ACCEPT") or line.startswith("REJECT"):
                break

        p.terminate()

    return dict(counts)


def select_hot_edges(
    edge_counts: Dict[Tuple[int, int], int],
    mass_target: float,
    max_edges: int,
) -> Tuple[List[Tuple[int, int]], float]:
    """Pick the smallest prefix of edges covering `mass_target` of observed probes."""

    if not edge_counts:
        return [], 0.0

    total = sum(edge_counts.values())
    items = sorted(edge_counts.items(), key=lambda kv: kv[1], reverse=True)
    hot: List[Tuple[int, int]] = []
    acc = 0
    for (u, v), c in items:
        if len(hot) >= max_edges:
            break
        hot.append((u, v))
        acc += c
        if acc / total >= mass_target:
            break
    return hot, (acc / total if total else 0.0)


# ---------------------------- Weighted local search ----------------------------


def build_weighted_adj(n: int, edge_counts: Dict[Tuple[int, int], int]) -> List[List[Tuple[int, int]]]:
    wadj: List[List[Tuple[int, int]]] = [[] for _ in range(n)]
    for (u, v), w in edge_counts.items():
        wadj[u].append((v, w))
        wadj[v].append((u, w))
    return wadj


def weighted_conflict_mass(colors: Sequence[int], edge_counts: Dict[Tuple[int, int], int]) -> Tuple[int, int]:
    bad = 0
    total = 0
    for (u, v), w in edge_counts.items():
        total += w
        if colors[u] == colors[v]:
            bad += w
    return bad, total


def count_conflicting_edges(colors: Sequence[int], edges: Sequence[Tuple[int, int]]) -> int:
    bad = 0
    for u, v in edges:
        if colors[u] == colors[v]:
            bad += 1
    return bad


def vertex_marginal_mass(n: int, edge_counts: Dict[Tuple[int, int], int]) -> List[int]:
    mass = [0] * n
    for (u, v), w in edge_counts.items():
        mass[u] += w
        mass[v] += w
    return mass


def total_weighted_bad(colors: Sequence[int], weighted_adj: List[List[Tuple[int, int]]]) -> int:
    bad = 0
    for u in range(len(colors)):
        cu = colors[u]
        for v, w in weighted_adj[u]:
            if u < v and cu == colors[v]:
                bad += w
    return bad


def build_weighted_edge_list(edge_counts: Dict[Tuple[int, int], int]) -> Tuple[List[Tuple[int, int, int]], List[int], int]:
    """Return (edges, prefix_sums, total_weight) for weighted sampling."""

    edges: List[Tuple[int, int, int]] = [(u, v, w) for (u, v), w in edge_counts.items()]
    edges.sort(key=lambda e: e[2], reverse=True)
    prefix: List[int] = []
    total = 0
    for _, _, w in edges:
        total += w
        prefix.append(total)
    return edges, prefix, total


def sample_weighted_edge(
    edges: List[Tuple[int, int, int]],
    prefix: List[int],
    total_w: int,
    rng: random.Random,
) -> Tuple[int, int, int]:
    if not edges or total_w <= 0:
        return (0, 0, 0)
    r = rng.randrange(total_w)
    # binary search prefix
    lo, hi = 0, len(prefix) - 1
    while lo < hi:
        mid = (lo + hi) // 2
        if r < prefix[mid]:
            hi = mid
        else:
            lo = mid + 1
    return edges[lo]


def run_verifier_once_collect_reject_edge(
    graph_rel: str,
    rounds: int,
    colors: Sequence[int],
    timeout_s: int = 15,
) -> Optional[Tuple[int, int]]:
    """Run the verifier once using a fixed coloring.

    Returns the rejecting monochromatic edge if the verifier rejects, else None.
    """

    cmd = ["wsl", "./zk_verifier", "--graph", graph_rel, "--rounds", str(rounds)]
    p = subprocess.Popen(
        cmd,
        cwd=BASE_DIR,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        encoding="utf-8",
        errors="replace",
        bufsize=1,
    )
    assert p.stdin and p.stdout

    start = time.time()
    reject_edge: Optional[Tuple[int, int]] = None
    try:
        while True:
            if time.time() - start > timeout_s:
                break

            line = p.stdout.readline()
            if not line:
                break
            line = line.strip()

            if line.startswith("CHALLENGE"):
                _, us, vs = line.split()
                u = int(us)
                v = int(vs)
                p.stdin.write(f"ANSWER {colors[u]} {colors[v]}\n")
                p.stdin.flush()
                continue

            if line.startswith("REJECT"):
                parts = line.split()
                # Expected format: REJECT monochromatic-edge u v
                ints = [int(x) for x in parts if x.isdigit()]
                if len(ints) >= 2:
                    u, v = ints[-2], ints[-1]
                    if u > v:
                        u, v = v, u
                    reject_edge = (u, v)
                break

            if line.startswith("ACCEPT"):
                break
    finally:
        p.terminate()

    return reject_edge


def read_coloring(path: str, n: int) -> List[int]:
    colors: List[int] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            colors.append(int(line))
    if len(colors) != n:
        raise ValueError(f"Coloring file has {len(colors)} entries, but graph has {n} vertices")
    for c in colors:
        if c not in (0, 1, 2):
            raise ValueError("Coloring must use only colors {0,1,2}")
    return colors


def run_protocol_trial(
    graph_rel: str,
    rounds: int,
    base_colors: Sequence[int],
    rng: random.Random,
    timeout_s: int = 20,
) -> Optional[bool]:
    """Run one protocol execution and return True/False.

    Returns None on timeout / I/O failure so caller can retry without biasing the estimate.
    """

    perm = [0, 1, 2]
    rng.shuffle(perm)

    cmd = ["wsl", "./zk_verifier", "--graph", graph_rel, "--rounds", str(rounds)]
    p = subprocess.Popen(
        cmd,
        cwd=BASE_DIR,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        encoding="utf-8",
        errors="replace",
        bufsize=1,
    )
    assert p.stdin and p.stdout

    q: queue.Queue[Optional[str]] = queue.Queue()

    def reader() -> None:
        try:
            for line in p.stdout:  # type: ignore[assignment]
                q.put(line)
        finally:
            q.put(None)

    t = threading.Thread(target=reader, daemon=True)
    t.start()

    deadline = time.time() + timeout_s
    try:
        while True:
            remaining = deadline - time.time()
            if remaining <= 0:
                return None
            try:
                line = q.get(timeout=remaining)
            except queue.Empty:
                return None
            if line is None:
                return None
            line = line.strip()

            if line.startswith("CHALLENGE"):
                parts = line.split()
                if len(parts) < 3:
                    return None
                u = int(parts[1])
                v = int(parts[2])
                cu = perm[base_colors[u]]
                cv = perm[base_colors[v]]
                p.stdin.write(f"ANSWER {cu} {cv}\n")
                p.stdin.flush()
                continue

            if line.startswith("ACCEPT"):
                return True
            if line.startswith("REJECT"):
                return False
    finally:
        try:
            p.terminate()
        except Exception:
            pass
        try:
            p.kill()
        except Exception:
            pass


def repair_reject_edge(
    colors: List[int],
    u: int,
    v: int,
    weighted_adj: List[List[Tuple[int, int]]],
    forbidden: List[Set[int]],
) -> None:
    """Force (u,v) to be bichromatic by recoloring one endpoint with minimal delta."""

    if colors[u] != colors[v]:
        return

    def best_fix_for_vertex(x: int, other_color: int) -> Tuple[int, int]:
        old_c = colors[x]
        best_c = old_c
        best_delta = 10**18
        for new_c in (0, 1, 2):
            if new_c == old_c:
                continue
            if new_c == other_color:
                continue
            if new_c in forbidden[x]:
                continue
            delta = 0
            for nb, w in weighted_adj[x]:
                old_bad = w if old_c == colors[nb] else 0
                new_bad = w if new_c == colors[nb] else 0
                delta += new_bad - old_bad
            if delta < best_delta:
                best_delta = delta
                best_c = new_c
        return best_c, best_delta

    cu, du = best_fix_for_vertex(u, colors[v])
    cv, dv = best_fix_for_vertex(v, colors[u])
    if du <= dv:
        if cu != colors[u]:
            colors[u] = cu
    else:
        if cv != colors[v]:
            colors[v] = cv


def local_search_minimize_bad(
    colors: List[int],
    weighted_adj: List[List[Tuple[int, int]]],
    forbidden: List[Set[int]],
    steps: int,
    random_walk_prob: float,
    rng: random.Random,
) -> None:
    """Local search to minimize weighted monochromatic mass on probed edges.

    Uses a best-improving move most of the time, with occasional random walk
    steps to escape shallow local minima.
    """

    n = len(colors)
    nodes = list(range(n))

    # Prefer selecting endpoints of high-weight *currently conflicting* edges.
    # This empirically converges faster than uniform random vertices.
    # Note: edge_counts includes only probed edges, which is exactly what we optimize.
    edge_counts: Dict[Tuple[int, int], int] = {}
    for u in range(n):
        for v, w in weighted_adj[u]:
            if u < v:
                edge_counts[(u, v)] = edge_counts.get((u, v), 0) + w
    edges, prefix, total_w = build_weighted_edge_list(edge_counts)

    def best_recolor(v: int) -> Tuple[int, int]:
        old_c = colors[v]
        best_c = old_c
        best_delta = 0
        for new_c in (0, 1, 2):
            if new_c == old_c or new_c in forbidden[v]:
                continue
            delta = 0
            for nb, w in weighted_adj[v]:
                old_bad = w if old_c == colors[nb] else 0
                new_bad = w if new_c == colors[nb] else 0
                delta += new_bad - old_bad
            if delta < best_delta:
                best_delta = delta
                best_c = new_c
        return best_c, best_delta

    for _ in range(steps):
        if rng.random() < random_walk_prob:
            v = rng.choice(nodes)
            old_c = colors[v]
            cand = [c for c in (0, 1, 2) if c != old_c and c not in forbidden[v]]
            if cand:
                colors[v] = rng.choice(cand)
            continue

        u, v, _w = sample_weighted_edge(edges, prefix, total_w, rng)
        if u == v:
            continue
        if colors[u] != colors[v]:
            continue

        # Try to fix the conflict by recoloring one endpoint.
        cu, du = best_recolor(u)
        cv, dv = best_recolor(v)
        if du == 0 and dv == 0:
            continue
        if du <= dv:
            colors[u] = cu
        else:
            colors[v] = cv


def build_unit_adj(n: int, edges: Sequence[Tuple[int, int]]) -> List[List[int]]:
    adj: List[List[int]] = [[] for _ in range(n)]
    for u, v in edges:
        adj[u].append(v)
        adj[v].append(u)
    return adj


def local_search_reduce_total_conflicts(
    colors: List[int],
    edges: Sequence[Tuple[int, int]],
    unit_adj: List[List[int]],
    weighted_adj: List[List[Tuple[int, int]]],
    forbidden: List[Set[int]],
    steps: int,
    rng: random.Random,
    alpha_weighted: int = 10,
    beta_unweighted: int = 1,
    random_walk_prob: float = 0.03,
) -> None:
    """Try to reduce total number of monochromatic edges while keeping weighted bad mass low.

    Objective uses a linear combination:
      score = alpha_weighted * (delta weighted-bad) + beta_unweighted * (delta unweighted-bad)
    """

    n = len(colors)
    nodes = list(range(n))

    def delta_unweighted(v: int, old_c: int, new_c: int) -> int:
        d = 0
        for nb in unit_adj[v]:
            d -= 1 if old_c == colors[nb] else 0
            d += 1 if new_c == colors[nb] else 0
        return d

    def delta_weighted(v: int, old_c: int, new_c: int) -> int:
        d = 0
        for nb, w in weighted_adj[v]:
            d -= w if old_c == colors[nb] else 0
            d += w if new_c == colors[nb] else 0
        return d

    for _ in range(steps):
        v = rng.choice(nodes)
        old_c = colors[v]

        if rng.random() < random_walk_prob:
            cand = [c for c in (0, 1, 2) if c != old_c and c not in forbidden[v]]
            if cand:
                colors[v] = rng.choice(cand)
            continue

        best_c = old_c
        best_score = 0
        for new_c in (0, 1, 2):
            if new_c == old_c or new_c in forbidden[v]:
                continue
            dw = delta_weighted(v, old_c, new_c)
            du = delta_unweighted(v, old_c, new_c)
            score = alpha_weighted * dw + beta_unweighted * du
            if score < best_score:
                best_score = score
                best_c = new_c
        if best_c != old_c:
            colors[v] = best_c


# ---------------------------- Main solver ----------------------------


def solve_one_graph(graph_path: str, coloring_path: str, probe: ProbeConfig, solve_cfg: SolveConfig) -> Dict[str, float]:
    n, edges = read_graph(graph_path)
    if n == 0:
        write_coloring(coloring_path, [])
        return {"n": 0, "m": 0, "hot_mass": 0.0, "bad_mass": 1.0, "pred_accept": 0.0}

    rng = random.Random(solve_cfg.seed + n)

    # Full adjacency (for DSATUR on hot edges only we still need adjacency list)
    adj: List[List[int]] = [[] for _ in range(n)]
    for u, v in edges:
        adj[u].append(v)
        adj[v].append(u)

    graph_rel = rel_to_base(graph_path)
    edge_counts = probe_edge_distribution(graph_rel, probe)
    if not edge_counts:
        # Fallback: random coloring (should not happen)
        colors = [rng.randrange(3) for _ in range(n)]
        write_coloring(coloring_path, colors)
        return {"n": float(n), "m": float(len(edges)), "hot_mass": 0.0, "bad_mass": 1.0, "pred_accept": 0.0}

    # Identify the "hub" vertex under the *observed* distribution.
    v_mass = vertex_marginal_mass(n, edge_counts)
    hub = max(range(n), key=lambda v: v_mass[v])

    total_probe = sum(edge_counts.values())
    hub_mass_total = v_mass[hub] / max(1, 2 * total_probe)

    colors, hub_from_solver, protected_hub_mass = compute_adversarial_coloring(
        n=n,
        edges=edges,
        adj=adj,
        edge_counts=edge_counts,
        solve_cfg=solve_cfg,
        rng=rng,
    )
    hub = hub_from_solver
    forbidden: List[Set[int]] = [set() for _ in range(n)]

    # Optional feedback fine-tuning: only worth doing when we're already near the target.
    base_bad_w, base_total_w = weighted_conflict_mass(colors, edge_counts)
    base_bad_mass = (base_bad_w / base_total_w) if base_total_w else 1.0
    if solve_cfg.feedback_iters > 0 and base_bad_mass <= 0.03:
        for _ in range(solve_cfg.feedback_iters):
            rej = run_verifier_once_collect_reject_edge(
                graph_rel=graph_rel,
                rounds=solve_cfg.feedback_rounds,
                colors=colors,
            )
            if rej is None:
                break
            u, v = rej
            repair_reject_edge(
                colors=colors,
                u=u,
                v=v,
                weighted_adj=weighted_adj,
                forbidden=forbidden,
            )
            local_search_minimize_bad(
                colors=colors,
                weighted_adj=weighted_adj,
                forbidden=forbidden,
                steps=max(4_000, solve_cfg.steps_per_restart // 10),
                random_walk_prob=solve_cfg.random_walk_prob,
                rng=rng,
            )

    # Output
    write_coloring(coloring_path, colors)

    # Metrics
    bad_w, total_w = weighted_conflict_mass(colors, edge_counts)
    bad_mass = (bad_w / total_w) if total_w else 1.0
    pred_accept = (1.0 - bad_mass) ** ROUNDS_PER_PROTOCOL if bad_mass < 1.0 else 0.0

    # Also report how invalid the coloring is on the full edge set (assignment writeup requirement).
    bad_edges = count_conflicting_edges(colors, edges)
    bad_edge_frac = (bad_edges / len(edges)) if edges else 0.0
    return {
        "n": float(n),
        "m": float(len(edges)),
        "hub": float(hub),
        "hub_mass": float(hub_mass_total),
        "protected_hub_mass": float(protected_hub_mass),
        "bad_edges": float(bad_edges),
        "bad_edge_frac": float(bad_edge_frac),
        "bad_mass": float(bad_mass),
        "pred_accept": float(pred_accept),
        "observed_edges": float(len(edge_counts)),
        "hub_deg": float(len(adj[hub])),
    }


def run_experiment(graph_path: str, coloring_path: str) -> Tuple[float, int]:
    """Return (accept_rate, completed_trials)."""

    graph_rel = rel_to_base(graph_path)
    n, _edges = read_graph(graph_path)
    base_colors = read_coloring(coloring_path, n)

    rng = random.Random(99991 + n)
    default_trials = 8 if FAST_MODE else TRIALS_PER_GRAPH
    target_trials = _env_int("Q3_TRIALS", default_trials)
    timeout_s = _env_int("Q3_TRIAL_TIMEOUT_S", 15 if FAST_MODE else 25)
    accepts = 0
    completed = 0
    attempts = 0
    max_attempts = target_trials * 5
    while completed < target_trials and attempts < max_attempts:
        attempts += 1
        out = run_protocol_trial(
            graph_rel=graph_rel,
            rounds=ROUNDS_PER_PROTOCOL,
            base_colors=base_colors,
            rng=rng,
            timeout_s=timeout_s,
        )
        if out is None:
            continue
        completed += 1
        if out:
            accepts += 1

    rate = (accepts / completed) if completed else 0.0
    return rate, completed


def main() -> None:
    ensure_dirs()
    print("Q3: bias-probing + hot-edge coloring", flush=True)

    # Sizes used previously in this workspace
    if SIZE_PROFILE == "high":
        sizes = [
            50,
            60,
            70,
            80,
            90,
            100,
            120,
            150,
            200,
            250,
            300,
            350,
            400,
            450,
            500,
            600,
            700,
            800,
            900,
            1000,
        ]
    else:
        sizes = [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 90, 100, 120, 150, 200, 300, 400, 500, 800, 1000]
    sizes = sizes[:NUM_GRAPHS]

    # Probing: keep it fast but informative. One run is usually enough; increase if noisy.
    def probe_for_size(n: int) -> ProbeConfig:
        # More probe rounds = less mismatch between predicted and measured acceptance.
        # You can scale globally via env var Q3_PROBE_MULT (e.g., 2.0).
        if n <= 30:
            base = 1200
        elif n <= 120:
            base = 2800
        elif n <= 400:
            base = 4200
        else:
            base = 6000
        rounds = max(400, int(base * PROBE_MULT))
        return ProbeConfig(rounds=rounds, runs=1)

    default_restarts = 5 if FAST_MODE else 12
    default_steps = 30_000 if FAST_MODE else 90_000
    solve_cfg = SolveConfig(
        restarts=_env_int("Q3_RESTARTS", default_restarts),
        steps_per_restart=_env_int("Q3_STEPS", default_steps),
        random_walk_prob=_env_float("Q3_RW_PROB", 0.06 if FAST_MODE else 0.05),
        feedback_iters=_env_int("Q3_FEEDBACK_ITERS", 0),
        feedback_rounds=_env_int("Q3_FEEDBACK_ROUNDS", 400),
        seed=_env_int("Q3_SEED", 12345),
    )

    FORCE_REGENERATE = False
    results_path = os.path.join(BASE_DIR, "results.txt")
    with open(results_path, "w", encoding="utf-8") as rf:
        rf.write(
            "ID\tSize\tHub\tHubMass\tProtectedHubMass\tHubDeg\tBadEdges\tBadEdgeFrac\tBadMass\tPredAccept\tAcceptRate\tObsEdges\tCompletedTrials\n"
        )

    rows: List[Tuple[int, int, Dict[str, float], float]] = []
    for i, size in enumerate(sizes, start=1):
        print(f"\n[{i}/{NUM_GRAPHS}] size={size}", flush=True)
        print(f"Selecting adversarial graph ({CANDIDATE_GRAPHS_PER_SIZE} candidates)...", flush=True)
        g_path = generate_best_graph(i, size, force_regenerate=FORCE_REGENERATE)
        c_path = os.path.join(BASE_DIR, COLORINGS_DIR, f"coloring_{i}.txt")

        probe_cfg = probe_for_size(size)
        metrics = solve_one_graph(g_path, c_path, probe_cfg, solve_cfg)

        print(
            f"  probe: rounds={probe_cfg.rounds} runs={probe_cfg.runs} | "
            f"hub={int(metrics['hub'])} hub_mass≈{metrics['hub_mass']:.3f} protected≈{metrics['protected_hub_mass']:.3f} "
            f"hub_deg={int(metrics['hub_deg'])} "
            f"obs_edges={int(metrics['observed_edges'])}",
            flush=True,
        )
        print(
            f"  invalid: bad_edges={int(metrics['bad_edges'])}/{int(metrics['m'])} "
            f"({metrics['bad_edge_frac']*100:.2f}%)",
            flush=True,
        )
        print(
            f"  estimated: bad_mass≈{metrics['bad_mass']:.4f} pred_accept≈{metrics['pred_accept']*100:.1f}%",
            flush=True,
        )
        exp_bad_hits = ROUNDS_PER_PROTOCOL * metrics["bad_mass"]
        print(f"  estimated: expected_bad_hits≈{exp_bad_hits:.2f} per {ROUNDS_PER_PROTOCOL} rounds", flush=True)

        rate, completed = run_experiment(g_path, c_path)
        denom = (8 if FAST_MODE else TRIALS_PER_GRAPH)
        extra = f" (completed {completed}/{denom})" if completed != denom else ""
        print(f"  measured:  accept_rate={rate*100:.1f}%{extra}", flush=True)

        rows.append((i, size, metrics, rate))
        with open(results_path, "a", encoding="utf-8") as rf:
            rf.write(
                f"{i}\t{size}\t{int(metrics['hub'])}\t{metrics['hub_mass']:.3f}\t{metrics['protected_hub_mass']:.3f}\t{int(metrics['hub_deg'])}\t"
                f"{int(metrics['bad_edges'])}\t{metrics['bad_edge_frac']:.6f}\t"
                f"{metrics['bad_mass']:.4f}\t{metrics['pred_accept']:.4f}\t{rate:.4f}\t{int(metrics['observed_edges'])}\t{completed}\n"
            )

    avg = sum(r for _, _, _, r in rows) / len(rows)
    print(f"\nAverage acceptance over {len(rows)} graphs: {avg*100:.1f}%", flush=True)


if __name__ == "__main__":
    main()
